### ISSUE TITLE
Article redirect error

### ISSUE THREAD

**Issue by felipesousa** [webcomponents/webcomponents.github.io#363] opened 2016-10-29 03:22 UTC
I dont know if this error happens elsewhere in the site, but trying to access a particular article ([A Quick Introduction To Polymer](http://webcomponents.org/articles/a-quick-polymer-introduction) ), I came across a redirect problem when trying to access the article page, follow the example below: 

<img src="http://g.recordit.co/j9m6pJihBT.gif" />

the same error occurs in versions of google chrome and canary.

**Comment by Nevraeka** [comment] 2016-10-31 14:25
I think this is a duplicate of #362 so I am going to close this ticket. this effects 2 pages as far as I can see. I don't know why this is happening ATM but I will fix it ASAP ( I am swamped with work for the next few days) This is a fairly obnoxious little bug and if you or someone else would like to fix it earlier than I can get to it, I am more than happy to merge a Pull Request :) thanks @felipesousa

**Closed by Nevraeka** 2016-10-31 14:25 UTC

**Comment by felipesousa** [comment] 2016-10-31 15:05
@Nevraeka thanks for your response, I try this error in local, but, without success! I go better search this error and as resolve that. Hug!
